### ISSUE TITLE
Infinite loop on EOF check

### ISSUE THREAD

**Issue by noizex** [baszalmstra/header-parser#6]
Hello again! Sorry to bother you - after updating to recent master to have the template parsing, I encountered a problem when tokenizer gets into infinite loop. I think it may be caused by this change:

https://github.com/baszalmstra/header-parser/commit/c18dd5202b2b6b71f3fd413859b1a256f44a59c6

as reverting to commit before this does not have this problem.

**Comment by baszalmstra** [comment]
Oh thats not good! Ill look into it. Would you be able to post a header
that causes the issue?

**Comment by baszalmstra** [comment]
Ah thanks! Ill look into it!

**Comment by baszalmstra** [comment]
I fixed the bug in https://github.com/baszalmstra/header-parser/commit/b78dff9c0accd3350c920708ce7045c37ab7dad8 . Sorry for you troubles!

**Comment by noizex** [comment]
No problem at all, happy to help testing this! Thanks for helping so fast :) I tried to find the cause but I'd have to understand the whole tokenzier routine so I failed completely. I found one or two more issues which I'll report in another ticket.
